### PR TITLE
Don't calculate sizes for Box that has Box children

### LINKED ISSUE #56: Initial bounding box calculation are wrong when using nested boxes
I used a message and codesandbox from a discord server
https://discord.com/channels/740090768164651008/745777196911689748/860103131593310238
https://codesandbox.io/s/playing-with-react-three-flex-forked-05wo8?file=/src/App.js

The problem is that initial bounding box for a group that contains other boxes is reported incorrectly (width should be 200, but it's 100). This probably has to do with that until flex is calculated first time, boxes inside other boxes positioned in the same place

### PR DESCRIPTION
**Pull request by saitonakamura**
Fixes #56

### CODE REVIEW

**Comment by talentlessguy** [comment]
would like to merge but asking in case, did you check test the PR locally?

**Comment by saitonakamura** [comment]
Yes, I tested it on a case from codesandbox and on the bunch of stories in storybook (I use that PR I've opened). Now that you've mentioned it I also checked the example and it's not working, but it's also not working for me locally in master

**Comment by saitonakamura** [comment]
Error is 
```
Failed to compile.

./src/index.js
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "/Users/saitonakamura/code/react-three-flex-copy/examples/node_modules/react-refresh/babel.js",
    "dirname": "/Users/saitonakamura/code/react-three-flex-copy/examples",
    "ownPass": false,
    "file": {
      "request": "/Users/saitonakamura/code/react-three-flex-copy/examples/node_modules/react-refresh/babel.js",
      "resolved": "/Users/saitonakamura/code/react-three-flex-copy/examples/node_modules/react-refresh/babel.js"
    }
  },
  {
    "alias": "/Users/saitonakamura/code/react-three-flex-copy/examples/node_modules/react-refresh/babel.js",
    "dirname": "/Users/saitonakamura/code/react-three-flex-copy/examples",
    "ownPass": false,
    "file": {
      "request": "/Users/saitonakamura/code/react-three-flex-copy/examples/node_modules/react-refresh/babel.js",
      "resolved": "/Users/saitonakamura/code/react-three-flex-copy/examples/node_modules/react-refresh/babel.js"
    }
  }
]
    at cachedFunction.next (<anonymous>)
^C
```
when you run `yarn start` in examples, so I'm pretty sure it's not my changes that broke it

**Comment by talentlessguy** [comment]
my bad I've updated react-scripts so this is the cause

**Comment by talentlessguy** [comment]
also i'll merge the storybook pr as well

**Comment by talentlessguy** [comment]
done. both pr merged @saitonakamura :P

**Comment by saitonakamura** [comment]
Yay thanks! This really helps (we're developing a ui for a vr so flex engine is pretty much a must have)

**Pull request merged**
