### PR TITLE
Upgrade to React 18

### LINKED ISSUE #78: typescript errors with r3f v8
Related to  [issue #2190 in r3f](https://github.com/pmndrs/react-three-fiber/issues/2190#issuecomment-1089246649)

### PR DESCRIPTION
**Pull request by giulioz**
Fixes #78

### CODE REVIEW

**Review by talentlessguy — APPROVED** [review]

**Comment by talentlessguy** [comment]
Netlify seems to fail because of `"engines"` of some package

**Comment by giulioz** [comment]
Any idea on how to fix it?

**Comment by talentlessguy** [comment]
we need to bump Node.js version on netlify somehow

**Comment by talentlessguy** [comment]
anyways i'll merge it

**Pull request merged**
